version: '3.5'
services:
  mongo:
    image: mongo
    container_name: clav_mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
  graphdb:
    image: jcm300/clav_graphdb:1.0.4
    container_name: clav_graphdb
    build:
      context: ./graphdb
      dockerfile: Dockerfile
    restart: always
    volumes:
      - graphdb-data:/opt/graphdb/home/data/repositories
    ports:
      - "7200:7200"
  server:
    image: jcm300/clav_api:1.0.4
    container_name: clav_server
    build:
      context: ./../CLAV2018/
      dockerfile: Dockerfile
    restart: always
    environment:
      - SWAGGER_URL=http://localhost:7779
      - GRAPHDB=graphdb:7200
      - MONGODB=mongo
    links:
      - mongo
      - graphdb
    ports:
      - "7779:7779"
volumes:
  mongodb-data:
    external: false
    name: clav-mongodb-data
  graphdb-data:
    external: false
    name: clav-graphdb-data
