version: '3.5'
services:
  mongo:
    image: mongo:4.2
    container_name: clav_mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
  graphdb:
    image: ${GRAPHDB_IMG}
    container_name: clav_graphdb
    build:
      context: ./graphdb
      dockerfile: Dockerfile
      args:
        - version=${GRAPHDB_VERSION}
        - dataFile=${GRAPHDB_DATA_FILE}
    restart: always
    volumes:
      - graphdb-data:/opt/graphdb/home/data/repositories
  server:
    image: ${SERVER_IMG}
    container_name: clav_server
    build:
      context: ./../CLAV2018/
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - SWAGGER_URL=${SWAGGER_URL}
      - GRAPHDB=graphdb:7200
      - MONGODB=mongo
      - API_VERSION=${API_VERSION}
      - INTERFACE_HOSTS=${INTERFACE_HOSTS}
  interface:
    image: ${INTERFACE_IMG}
    container_name: interface
    build:
      context: ./../CLAV2019/
      dockerfile: Dockerfile
      args:
        - VUE_APP_API_URL=${API_URL}
        - VUE_APP_API_VERSION=${API_VERSION}
    restart: always
    environment:
      - SERVER_URL=http://server:7779
      - CERTS_API=${CERT_API_FOLDER}
      - CERTS_INT=${CERT_INT_FOLDER}
      - API_VERSION=${API_VERSION}
      - DOMAINS_SERVER=${DOMAINS_SERVER}
      - DOMAINS_INTERFACE=${DOMAINS_INTERFACE}
    volumes:
      - ${PWD}/${NGINX_FILE}:/etc/nginx/nginx.conf.template
      - ${PWD}/beforeStart.sh:/beforeStart.sh
      - ${PWD}/afterStart.sh:/afterStart.sh
      - acme-data:${ACME_FOLDER}
      - crontabs:/var/spool/cron/crontabs/
    command: /bin/bash -c "/beforeStart.sh ${CERT_API_FOLDER} && /beforeStart.sh ${CERT_INT_FOLDER} && envsubst '$$SERVER_URL $$CERTS_API $$CERTS_INT $$API_VERSION $$DOMAINS_SERVER $$DOMAINS_INTERFACE' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && (nginx -g 'daemon off;' &) && /afterStart.sh -c ${CERT_API_FOLDER} -a ${ACME_FOLDER} ${DOMAINS_SERVER} && /afterStart.sh -c ${CERT_INT_FOLDER} -a ${ACME_FOLDER} ${DOMAINS_INTERFACE} && tail -f /dev/null"
    ports:
      - "${HTTP_PORT}:7779"
      - "${HTTPS_PORT}:7780"
volumes:
  mongodb-data:
    external: false
    name: clav-mongodb-data
  graphdb-data:
    external: false
    name: clav-graphdb-data
  acme-data:
    external: false
    name: acme-data
  crontabs:
    external: false
    name: crontabs
