version: '3.5'
services:
  mongo:
    image: mongo
    container_name: clav_mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
  graphdb:
    image: jcm300/clav_graphdb:1.0.6
    container_name: clav_graphdb
    restart: always
    volumes:
      - graphdb-data:/opt/graphdb/home/data/repositories
  server:
    image: jcm300/clav_api:1.0.6
    container_name: clav_server
    restart: always
    environment:
      - SWAGGER_URL=http://localhost:7779
      - GRAPHDB=graphdb:7200
      - MONGODB=mongo
    ports:
      - "7779:7779"
  interface:
    image: jcm300/clav_interface:1.0.6
    container_name: clav_interface
    restart: always
    environment:
      - API_URL=server:7779
  nginx:
    image: nginx
    container_name: clav_nginx
    restart: always
    volumes:
      - ${PWD}/nginx-template.conf:/etc/nginx/nginx.conf.template
    environment:
      - SERVER_URL=http://server:7779
      - INTERFACE_URL=http://interface:7780
    ports:
      - "8080:8080"
    command: /bin/bash -c "envsubst '$$SERVER_URL $$INTERFACE_URL' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
volumes:
  mongodb-data:
    external: false
    name: clav-mongodb-data
  graphdb-data:
    external: false
    name: clav-graphdb-data
