version: '3.5'
services:
  mongo:
    image: mongo:4.2
    container_name: clav_mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
  graphdb:
    image: ${GRAPHDB_IMG}
    container_name: clav_graphdb
    restart: always
    volumes:
      - graphdb-data:/opt/graphdb/home/data/repositories
  server:
    image: ${SERVER_IMG}
    container_name: clav_server
    restart: always
    environment:
      - NODE_ENV=production
      - PROTOCOLS=https
      - DOMAINS=${DOMAINS}
      - GRAPHDB=graphdb:7200
      - MONGODB=mongo
      - API_VERSION=${API_VERSION}
      - INTERFACE_HOSTS=${INTERFACE_HOSTS}
      - SERVER_AUTH_HOST=clav_auth:7778
  clav-auth:
    image: ${SERVER_AUTH_IMG}
    container_name: clav_auth
    restart: always
    environment:
      - NODE_ENV=production
      - API_VERSION=${API_VERSION}
      - API_HOST=server:7779
  kong:
    image: kong:2.0.4-ubuntu
    container_name: clav_kong
    restart: always
    environment:
      - DOMAINS=${DOMAINS}
      - EMAIL=${EMAIL}
      - API_VERSION=${API_VERSION}
      - API_HOST=server:7779
      - SERVER_AUTH_HOST=clav_auth:7778
    ports:
      - ${HTTP_PORT}:8000
      - ${HTTPS_PORT}:8443
      # admin
      # 8001:8001
      # 8444:8444
    volumes:
      - ${PWD}/kong/kong.conf:/etc/kong/kong.conf
      - ${PWD}/kong/kong.yml.template:/usr/local/kong/declarative/kong.yml.template
      - ${PWD}/beforeStart.sh:/beforeStart.sh
      - ${PWD}/afterStart.sh:/afterStart.sh
      - acme-data:/acme
    command: /bin/bash -c "/beforeStart.sh && envsubst '$$API_VERSION $$DOMAINS $$EMAIL $$DOMAINS_LIST' < /usr/local/kong/declarative/kong.yml.template > /usr/local/kong/declarative/kong.yml && (kong docker-start &) && afterStart.sh && tail -f /dev/null"
volumes:
  mongodb-data:
    external: false
    name: clav-mongodb-data
  graphdb-data:
    external: false
    name: clav-graphdb-data
  acme-data:
    external: false
    name: clav-acme-data
